# workflow to build and push docker image to AWS ECR (Elastic Container Registory)

name: Deploy to ECR

# workflow execution
on:
  # Triggers the workflow on push, when any cahnges are done in repo on master branch
  push:
    branches: [ master ]
  
  # Allow Manually trigger the workflow from GitHuB Action tab
  workflow_dispatch:

env:
  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
  ECR_REPOSITORY: docker_nodejs_demo
  IMAGE_TAG: nodejs_action_demo
  
#Jobs to build, configure and push 
jobs:

  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
  
  configure:
    needs: checkout
    runs-on: ubuntu-latest
    steps:  
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

  Build-image:
    needs: configure
    runs-on: ubuntu-latest
    steps:
    - name: Build and tag image 
      run: docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

  push-image:
      needs: Build-image
      runs-on: ubuntu-latest
      steps:
      - name: push image to Amazon ECR
        run: docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
