# workflow to build and push docker image to AWS ECR (Elastic Container Registory)

name: Deploy to Google Registry

# workflow execution
on:
  # Triggers the workflow on push, when any cahnges are done in repo on master branch
  push:
    branches: [ master ]
  
  # Allow Manually trigger the workflow from GitHuB Action tab
  workflow_dispatch:
  
#Jobs to build, configure and push 
jobs:

  Deployment:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
   
    - id: 'GCP-Auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.gcp_credentials }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      
    - name: 'GCP SETUP'
      uses: 'google-github-actions/setup-gcloud@v0.6.0'
      with:
        project_id: 'flash-span-372817'
        
#     - name: "Setup gcloud CLI"
#       uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
#       with:
#         version: '270.0.0'
#         service_account_key: ${{ secrets.gcp_credentials }}
#     - run: |
#         gcloud auth configure-docker
        
    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Build, tag and push image to ECR
      env:
        IMAGE: us-central1-docker.pkg.dev/flash-span-372817/demo
        IMAGE_TAG: gcp_demo
      run: |
        docker build -t $IMAGE:$IMAGE_TAG .
        
    #    docker push gcr.io/$IMAGE:$IMAGE_TAG
    
    - name: Push image
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE:$IMAGE_TAG us-central1-docker.pkg.dev/flash-span-372817/demo
        docker push us-central1-docker.pkg.dev/flash-span-372817/demo
 





          
